Fix errors due to using CFLAGS -Wall -Werror
vmod_querystring.c: In function 'apply_filter':
vmod_querystring.c:301:14: error: unused variable 'params' [-Werror=unused-variable]